In [2]:
import numpy as np

In [12]:
# a simple mini-batch implementation using numpy 
def batch_normalization_forward(x, gamma, beta, eps=1e-8):
    N, D = x.shape
    
    # Step 1: Calculate mean
    mu = np.mean(x, axis=0)
    
    # Step 2: Subtract mean
    xmu = x - mu
    
    # Step 3: Calculate variance
    var = np.mean(xmu**2, axis=0)
    
    # Step 4: Calculate standard deviation
    std = np.sqrt(var + eps)
    
    # Step 5: Invert standard deviation
    istd = 1.0 / std
    
    # Step 6: Normalize
    xhat = xmu * istd
    
    # Step 7: Scale and shift
    out = gamma * xhat + beta
    
    # Store intermediate values for backpropagation
    cache = (xhat, gamma, xmu, istd, std, var, eps)
    
    return out, cache

# Example usage
np.random.seed(100)
x = np.random.randn(100, 3)  # Input data
gamma = np.ones(3)           # Scale parameter
beta = np.zeros(3)           # Shift parameter

# Perform batch normalization forward pass
out, cache = batch_normalization_forward(x, gamma, beta)

print("Output shape:", out.shape)
print(f"Before normalize:\n{x[:5]}")
print("After Normalized:",out[:5])

Output shape: (100, 3)
Before normalize:
[[-1.74976547  0.3426804   1.1530358 ]
 [-0.25243604  0.98132079  0.51421884]
 [ 0.22117967 -1.07004333 -0.18949583]
 [ 0.25500144 -0.45802699  0.43516349]
 [-0.58359505  0.81684707  0.67272081]]
After Normalized: [[-1.55299144  0.35224236  1.0755908 ]
 [-0.12879852  0.96162304  0.43654118]
 [ 0.3216836  -0.99575654 -0.26742979]
 [ 0.35385336 -0.41178011  0.35745704]
 [-0.44378219  0.80468479  0.59510087]]
