In [26]:
import numpy as np

X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, -10, -11, 12]])

#### Standaization(Z-Score Normalization):
`Formula: (x - mean) / standard deviation`

In [27]:
def standardize_features(X):
    np_mean= np.mean(X, axis=0)
    np_std=np.std(X, axis=0)
    standardize_X=(X-np_mean)/np_std
    return standardize_X

#### Normalization (Min-Max scaling):[0-1]
`Formula: (x - min) / (max - min)`

In [28]:
def min_max_features(X, axis=1):
    min_val = np.min(X, axis)
    max_val = np.max(X, axis)
    normalized_X = (X - min_val) / (max_val - min_val)
    return normalized_X

In [29]:
std_nor= standardize_features(X)
min_max_nor= min_max_features(X,0)
print("Standarization:", std_nor)
print("Min-Max-Scaling:", min_max_nor)
print(min_max_features(X,0))

Standarization: [[-1.22474487  0.39223227  0.43193421 -1.22474487]
 [ 0.          0.98058068  0.95025527  0.        ]
 [ 1.22474487 -1.37281295 -1.38218948  1.22474487]]
Min-Max-Scaling: [[0.         0.75       0.77777778 0.        ]
 [0.5        1.         1.         0.5       ]
 [1.         0.         0.         1.        ]]
[[0.         0.75       0.77777778 0.        ]
 [0.5        1.         1.         0.5       ]
 [1.         0.         0.         1.        ]]


### Computer Vision
### Zero-centering/ Zero Centered Or Mean Centered
Subtracting the mean of each image from the corresponding image pixels helps to center the pixel values around zero.
`Formula: X -= np.mean(X, axis = 0)`
- Preserves the overall brightness and contrast of the image.
- Useful for image processing tasks that rely on relative pixel intensity values.
- Minimizes the effect of global lighting variations or biases across images.

In [34]:
def zero_centering_features(X, axis=0):
    return X-np.mean(X, axis)

zero_centering_features(X)

array([[ -4.        ,   2.66666667,   3.33333333,  -4.        ],
       [  0.        ,   6.66666667,   7.33333333,   0.        ],
       [  4.        ,  -9.33333333, -10.66666667,   4.        ]])

#### Standardization (X /= np.std(X, axis=1)):
Dividing each image by its standard deviation aims to scale the pixel values to have unit variance.
- The pixel intensities may be spread out over a larger dynamic range, potentially reducing the ability to differentiate fine details or low-intensity features.
- The scaling effect can amplify the impact of noise or artifacts present in the image.

In [36]:
def zero_std_features(X, axis=0):
    return X/np.mean(X, axis)

zero_std_features(X)

array([[  0.2,  -3. ,  -9. ,   0.5],
       [  1. ,  -9. , -21. ,   1. ],
       [  1.8,  15. ,  33. ,   1.5]])

#### Per Channel Mean:
Per channel mean refers to calculating the mean value separately for each channel of an image. In the context of image processing, an image typically consists of multiple color channels, such as Red, Green, and Blue (RGB).

In [43]:
image = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

# Calculate per channel mean
mean_per_channel = np.mean(image, axis=(0, 1))

print("Per channel mean:", mean_per_channel)
print("Subtract mean Image:",zero_centering_features(image))

print("Subtract Per-Chanel:", zero_centering_features(image, (0,1)))

Per channel mean: [13. 14. 15.]
Subtract mean Image: [[[-9. -9. -9.]
  [-9. -9. -9.]
  [-9. -9. -9.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 9.  9.  9.]
  [ 9.  9.  9.]
  [ 9.  9.  9.]]]
Subtract Per-Chanel: [[[-12. -12. -12.]
  [ -9.  -9.  -9.]
  [ -6.  -6.  -6.]]

 [[ -3.  -3.  -3.]
  [  0.   0.   0.]
  [  3.   3.   3.]]

 [[  6.   6.   6.]
  [  9.   9.   9.]
  [ 12.  12.  12.]]]
