In [1]:
import numpy as np

In [8]:
class Propagation:
    def __init__(self, input_size, hidden_size, output_size):
        np.random.seed(00)
        self.W1= np.random.randn(input_size, hidden_size)
        self.b1 = np.zeros((1, hidden_size))
        self.W2 = np.random.randn(hidden_size, output_size)
        self.b2 = np.zeros((1, output_size))
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return self.sigmoid(x) * (1 - self.sigmoid(x))
    
    def forward_propagation(self, X):
        self.hidden_layer_input = np.dot(X, self.W1) + self.b1
        self.hidden_layer_activation = self.sigmoid(self.hidden_layer_input) # added activation for non-linearity
        self.output_layer_input = np.dot(self.hidden_layer_activation, self.W2) + self.b2
        self.output = self.sigmoid(self.output_layer_input) # calculate the output
        return self.hidden_layer_activation, self.output
    
    # Define the backpropagation function
    def backpropagation(self, X, y):
        self.error = y - self.output
        self.output_delta = self.error * self.sigmoid_derivative(self.output)
        self.hidden_layer_error = np.dot(self.output_delta, self.W2.T)
        self.hidden_layer_delta = self.hidden_layer_error * self.sigmoid_derivative(self.hidden_layer_activation)
        return self.hidden_layer_delta, self.output_delta

# Example usage
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

input_size = X.shape[1]
hidden_size = 4
output_size = 1

# Create an instance of the NeuralNetwork class
p = Propagation(input_size, hidden_size, output_size)

# Forward propagation
hidden_layer_activation, output = p.forward_propagation(X)

# Backpropagation
hidden_layer_delta, output_delta = p.backpropagation(X, y)

# Print the results
print(f"Hidden layer activation:\n{hidden_layer_activation} \n Output:\n{output}")
print(f"Hidden layer delta:\n{hidden_layer_delta}\n Output:\n{output_delta}")

Hidden layer activation:
[[0.5        0.5        0.5        0.5       ]
 [0.86617546 0.27343225 0.72113296 0.46223277]
 [0.85371646 0.59872543 0.72685773 0.9038621 ]
 [0.97420925 0.3595954  0.87311946 0.88988196]] 
 Output:
[[0.72168765]
 [0.6897504 ]
 [0.82876192]
 [0.81259969]]
Hidden layer delta:
[[ 0.00385266 -0.01532565 -0.00537645 -0.05428096]
 [-0.00148476  0.00695431  0.00218849  0.02380024]
 [-0.00078319  0.00340418  0.00114631  0.01080831]
 [ 0.00355223 -0.01719516 -0.00517822 -0.05191785]]
 Output:
[[-0.15882788]
 [ 0.06902228]
 [ 0.03622499]
 [-0.17298694]]


In [ ]:
# define the sigmoid activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

In [3]:
def forward_propagation(X, weights, biases):
    layer_outputs=[X]
    for i in range(len(weights)):
        layer_input=np.dot(layer_outputs[-1], weights[i])+biases[i] # y= wx+b
        layer_activation= sigmoid(layer_input) # added activation ex=> sigmoid activation function
        layer_outputs.append(layer_activation)
    return layer_outputs

### for multiple neuron

In [10]:
# backward propagation: 2W^T*X
def back_propagation(X, y, layer_outputs, weights):
    errors=[y-layer_outputs[-1]]
    deltas=[errors[-1]*sigmoid_derivative(layer_outputs[-1])]
    for i in range(len(weights)-1,0,-1):
        error=np.dot(deltas[-1], np.transpose(weights[i]))
        errors.append(error)
        delta=errors[-1]*sigmoid_derivative(layer_outputs[i])
        deltas.append(delta)

    return deltas[::-1]

In [13]:
# defining the training function
def train(X,y, layer_sizes, num_epochs, learning_rate):
    # Initialize the weights and biases randomly
    np.random.seed(0)
    weights = []
    biases = []
    for i in range(len(layer_sizes) - 1):
        weights.append(np.random.randn(layer_sizes[i], layer_sizes[i+1]))
        biases.append(np.zeros((1, layer_sizes[i+1])))
    
    # Training loop
    for epoch in range(num_epochs):
        # Forward propagation
        layer_outputs = forward_propagation(X, weights, biases)

        # Backpropagation
        deltas = back_propagation(X, y, layer_outputs, weights)
        
        # Update the weights and biases
        for i in range(len(weights)):
            weights[i] += learning_rate * layer_outputs[i].T.dot(deltas[i])
            biases[i] += learning_rate * np.sum(deltas[i], axis=0)
        
    return weights, biases

In [14]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

layer_sizes = [2, 4, 4, 1]  # Input size, hidden layer sizes, output size
num_epochs = 10000
learning_rate = 0.1

weights, biases = train(X, y, layer_sizes, num_epochs, learning_rate)

# Make predictions
layer_outputs = forward_propagation(X, weights, biases)
predictions = layer_outputs[-1]
print("Predictions:", predictions)

Predictions: [[0.46067261]
 [0.51741939]
 [0.49491105]
 [0.51403026]]


In [7]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
layer_outputs = [X]
layer_outputs[-1]

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])